### ISSUE TITLE
Constructor without parameters not initalize all fields

### ISSUE THREAD

**Issue by defterai** [DuffsDevice/tinyutf8#10]
`	union{
		SSO		t_sso;
		NON_SSO	t_non_sso;
	};`

`SSO` / `NON_SSO` constructor is without initialization fields by zero.
So sometimes string can contain some content before assign anything.
This issue reproduce randomly (compiler MSVC2015 / 32 bit) when use `cpp_str()`

**Comment by DuffsDevice** [comment]
Thank you for spotting this!
