### ISSUE TITLE
utf8_string::get_num_codepoints: incorrect return value for multibytes

### ISSUE THREAD

**Issue by vadim-berman** [DuffsDevice/tinyutf8#12]
Hi Jakob,

I use your library for a variety of languages, and one of them is Chinese, where most characters consist of 3 bytes. The last part of the method seems to be looking for the end of buffer where, in fact, it should be looking for the end of the fragment. This is the problematic line:

`const char*	buffer_end = buffer + data_len;`

Try looking for any characters of this string (for example): 我给了老张三本书。

。 has to be 8, and it is returned as 6. 了 is a mess. 

The correction is simple. You need to substitute `data_len` by `index + byte_count`. I would also recommend changing the name to `fragment_end` to prevent misunderstanding. 

The following modified code works for me (I left `data_len` just in case): 

`const char*	fragment_end = buffer + (index + byte_count < data_len? index + byte_count : data_len);`

**Comment by DuffsDevice** [comment]
Hi Vadim!

You are perfectly right. `buffer + index + byte_count` is the right solution, since get_num_codepoints doesn't check boundaries.

Thank you for debugging, I was able to quickly fix it this way!

Best Regards
Jakob

**Comment by vadim-berman** [comment]
Hi Jakob,

Thanks for the quick response - appreciated! Glad it helped. 

Best regards, Vadim
