### ISSUE TITLE
append(char32_t) does not convert back to UTF-8?

### ISSUE THREAD

**Issue by vadim-berman** [DuffsDevice/tinyutf8#15]
Try calling, for example, `my_string.append(U'ü')`. The character will be garbled. 

The workaround is to convert it to a UTF-8 string in any form.

**Comment by DuffsDevice** [comment]
Hi Vadim!

Thanks for the spot! I have hopefully fixed this bug by fixing utf8_string::utf8_string( value_type ).
Please check again with the newest commit and tell me whether it worked.

Thanks
Jakob

**Comment by vadim-berman** [comment]
Hi Jakob,

Yep - this one is fine! Thank you very much. 

Best regads, Vadim

**Comment by DuffsDevice** [comment]
Yay!
