### ISSUE TITLE
Avoid memcpy?

### ISSUE THREAD

**Issue by kelas** [DuffsDevice/tinyutf8#17]
I must be overlooking something, but suppose I have a readonly mmap'ed utf8 file - how do I pass it to tinyutf8 without triggering a full memcpy? `std::string::assign()` seems to be doing just that.

**Comment by DuffsDevice** [comment]
Hi Kelas, currently, string manipulation without buffer ownership (as in memory mapped files) is not supported by tinyutf8. However, it is not supported by std::string either (and therefore not in std::string::assign as well).

You might add this into "Projects > Feature Requests", but I don't know if I or anyone else will find the time to implement it without resulting into too much runtime overhead in the library.

Thank you however for your interest, if there is anything else I can help you with, let me know.

Cheers,
Jakob

**Comment by kelas** [comment]
Hey Jakob,
you're right — what I had in mind is [std::string_view](https://en.cppreference.com/w/cpp/string/basic_string_view)

**Comment by DuffsDevice** [comment]
Oh, yes, std::string_view does not have memory ownership! Currently, But, you know, I would have to implement every single function in utf8_string in utf8_string_view, which I don't have the time for right now 🙊

**Comment by MoAlyousef** [comment]
> Oh, yes, std::string_view does not have memory ownership! But, you know [thinking about implementing string_view for utf8] I would have to implement most every function in utf8_string in utf8_string_view, which I don't have the time for right now 🙊

Not a solution, but a temporary one is 
A temporary implicit conversion operator like:
operator std::string_view() const { return std::string_view(data(), size()); }

Should allow passing utf8_string as a string view into functions, and all the string_view functions would be available. The user should be warned though on the gotchas associated with it (not being able to iterate over code points etc).
