### ISSUE TITLE
stringstream operator <<

### ISSUE THREAD

**Issue by marekfoltyn** [DuffsDevice/tinyutf8#2]
Hi, after replacing std::string with utf8_string, the following code shows error:

```cpp
utf8_string text = "hi";
stringstream stream;
stream << text; // error: no viable conversion from 'utf8_string' to 'string' 
```
In order to fix it, the last line must be modified: 

```cpp
 stream << text.c_str();
```

Is it possible to make utf8_string compatible with streams?
Thank you

**Comment by DuffsDevice** [comment]
This feature could be enabled by defining a certain macro, which you can look up in the header file. However, please refer to the latest commit (55), where I have made the defined by default.
Thank you for the notice!
