### ISSUE TITLE
Getting offset in characters / codepoints

### ISSUE THREAD

**Issue by vadim-berman** [DuffsDevice/tinyutf8#7]
How do I convert indexes / pointers to raw char* to codepoint / character offsets?

I was also looking at utilising the raw_get method, but I am not sure if it's the right thing to do:

`str.raw_get(offsetInBytes) - str.begin();`

PS. I posted it in Stackoverflow as well: https://stackoverflow.com/questions/49716774/tiny-utf8-getting-offset-in-characters-codepoints

**Comment by DuffsDevice** [comment]
Thank you for your question! The method `get_num_resulting_codepoints` was renamed in Version 2 to `get_num_codepoints` and additionally was made private.
I have drafted a new release ["2.0.2"][1], that makes `get_num_codepoints` public again (along with `get_num_bytes` and `get_num_bytes_from_start`).

You can use it the same way as you did before. However, the solution with subtracting iterators is a little bit more elegant as it does exactly the same and is equally efficient. I would stick to that one :)

Jakob

  [1]: https://github.com/DuffsDevice/tinyutf8/releases/tag/v2.0.2 "2.0.2"
