### ISSUE TITLE
Build issues with MSVC-2015

### ISSUE THREAD

**Issue by defterai** [DuffsDevice/tinyutf8#9]
Compilation with MSVC-2015 is failed with 2 issues:
1. `std::max` not found. Solution is simple - add  `#include <algorithm>` into source file
2. Function `__lzcnt64` is not available for 32 bit architecture. Solution just check for 32 bit mode by `#ifdef`

Also some M$ headers can contains - `#define max`
So better move `get_lut_width` implementation into source file.
I think other non trivial methods implementation can be moved into source file too. 
This is needed to reduce possible conflicts by such defines.

**Comment by DuffsDevice** [comment]
Fixed with pull request #11
